"""add grammar_topics and user_grammar_settings, update user and grammar_lesson

Revision ID: d7f1ed4224d5
Revises: 7feb8266b1ae
Create Date: 2026-07-07 18:29:19.355603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f1ed4224d5'
down_revision: Union[str, Sequence[str], None] = '7feb8266b1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False, comment='Thứ tự học (1-48)'),
    sa.Column('topic', sa.String(), nullable=False, comment='Tên chủ điểm ngữ pháp'),
    sa.Column('level', sa.String(length=2), nullable=False, comment='Trình độ: A1, A2, B1, B2'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Nhóm: Tenses, Sentence Structure, Vocabulary & Grammar'),
    sa.Column('description', sa.Text(), nullable=True, comment='Mô tả ngắn nội dung bài học'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Còn sử dụng trong curriculum không'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_topics_id'), 'grammar_topics', ['id'], unique=False)
    op.create_table('user_grammar_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK → users.id'),
    sa.Column('start_level', sa.String(length=2), nullable=True, comment='Trình độ đầu vào: A1/A2/B1/B2'),
    sa.Column('current_order', sa.Integer(), nullable=True, comment='Thứ tự topic đang học (order_num)'),
    sa.Column('daily_limit', sa.Integer(), nullable=True, comment='Số bài mới tối đa mỗi ngày'),
    sa.Column('last_study_date', sa.Date(), nullable=True, comment='Ngày học gần nhất (reset lessons_today)'),
    sa.Column('lessons_today', sa.Integer(), nullable=True, comment='Số bài đã học hôm nay'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Ngày tạo'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Ngày cập nhật'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_grammar_settings_id'), 'user_grammar_settings', ['id'], unique=False)
    op.add_column('grammar_lessons', sa.Column('topic_id', sa.Integer(), nullable=True, comment='FK → grammar_topics.id'))
    op.add_column('grammar_lessons', sa.Column('is_reviewed', sa.Boolean(), nullable=True, comment='Đã ôn tập lại bài này chưa'))
    op.alter_column('grammar_lessons', 'topic',
               existing_type=sa.VARCHAR(),
               comment='Tên chủ điểm ngữ pháp',
               existing_nullable=False)
    op.create_foreign_key(None, 'grammar_lessons', 'grammar_topics', ['topic_id'], ['id'])
    op.add_column('users', sa.Column('grammar_level', sa.String(length=2), nullable=True, comment='Trình độ ngữ pháp: A1/A2/B1/B2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grammar_level')
    op.drop_constraint(None, 'grammar_lessons', type_='foreignkey')
    op.alter_column('grammar_lessons', 'topic',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Tên chủ điểm ngữ pháp',
               existing_nullable=False)
    op.drop_column('grammar_lessons', 'is_reviewed')
    op.drop_column('grammar_lessons', 'topic_id')
    op.drop_index(op.f('ix_user_grammar_settings_id'), table_name='user_grammar_settings')
    op.drop_table('user_grammar_settings')
    op.drop_index(op.f('ix_grammar_topics_id'), table_name='grammar_topics')
    op.drop_table('grammar_topics')
    # ### end Alembic commands ###
